export const ESC_PRESETS = [
  "Pianoballade zum Auftakt",
  "Massive key change",
  "Tänzer:innen mit Flagge",
  "Jemand weint auf der Bühne",
  "Pyrotechnik",
  "LED-Kostüm",
  "Englisch + Landessprache gemischt",
  "Kommentar über den Moderator",
  "„We are one" im Text",
  "Schlagzeug-Solo",
  "Bizarre Requisite",
  "Jury gibt 12 Punkte an Nachbarland",
  "Jemand fällt fast hin",
  "Waving-Kamera-Fahrt",
  "Mittelalter-Ästhetik",
  "Drag-Performance",
  "Falsett-Moment",
  "Militärischer Marsch-Rhythmus",
  "Lichtshow geht schief",
  "Jemand spielt Violine selbst",
  "Nul points Kandidat:in",
  "Sprechendes Moderationsduo",
  "Technische Probleme",
  "Vogelperspektive-Kamera",
  "Herz-Geste ans Publikum",
  "Chor erscheint aus dem Nichts",
  "Kostümwechsel live",
  "Overdramatisches Ende",
  "Bestes Land scheidet im Halbfinale aus",
  "Ballon-Effekt",
  "Windmaschine im Dauereinsatz",
  "Reprise des Refrains als letzter Ton",
  "Moderator:in vergisst den Text",
  "Stimmungsmacher:in im Publikum gezeigt",
  "Postmoderner Ironie-Auftritt",
  "Glitzer-Konfetti-Regen",
  "Kinderchor im Hintergrund",
  "Unerwartetes Instrument (z.B. Dudelsack)",
  "„Douze points" mit langem Pause davor",
  "Sänger:in kniet am Ende nieder",
  "Ausdrucksstarke Mimik close-up",
  "Tänzer:in macht Split",
  "Feuersäulen auf der Bühne",
  "Handgeste zum Takt",
  "Hintergrundbildschirm mit Naturszenen",
];
